# fly.toml app configuration file generated for snowy-feather-9325 on 2023-10-26T16:55:19-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-feather-9325"
primary_region = "den"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
